name: Auto Merge and Delete Branch # ワークフローの名前

on: # ワークフローのトリガーとなるイベント
  pull_request:　# プルリクエストを対象
    branches:
      - main  # mainブランチへのプルリクエストを対象
    types: [opened]　# プルリクエストが新規作成された時のみ
    
jobs: # ジョブの定義
  auto-merge: # ジョブの名前
    runs-on: ubuntu-latest # # ジョブを実行する仮想環境

    steps:
      # step1 必要なパッケージ（GitHub CLI）をインストール
      - name: Install GitHub CLI
        run: brew install gh
        
      # step2 コードのチェックアウト
      - name: Check out code
        uses: actions/checkout@v2

      # step3 プルリクエストを自動でマージ，元のブランチを削除
      - name: Auto Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITBUN_TOKEN }}
        run: |
          PR_BRANCH=${{ github.event.pull_request.head.ref }}
          PR_NUMBER=${{ github.event.pullrequest.number }}

      # step4
      - name: Debug PR information
        run: echo "PR_BRANCH=${{ github.event.pull_request.head.ref }} PR_NUMBER=${{ github.pull_request.number}}"

          gh pr merge $PR_NUMBER --merge --admin --repo ${{ github.repository }}

          gh api -X DELETE "repos/${{ github.repository }}/git/refs/heads/${PR_BRANCH}"
